require:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - bin/**
    - db/**/*
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*
  TargetRubyVersion: 3.2

FactoryBot/AssociationStyle:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/LineEndStringConcatenationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Lint/AmbiguousBlockAssociation:
  AllowedMethods:
    - change

Lint/MissingSuper:
  Exclude:
    - app/graphql/sources/**/*

Lint/ReturnInVoidContext:
  Enabled: false

Layout/LineLength:
  Max: 180

Metrics/AbcSize:
  Max: 20
  Exclude:
    - app/avo/resources/**/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - config/environments/**/*.rb

Metrics/ClassLength:
  Max: 200
  CountAsOne:
    - array
    - hash

Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
  Max: 20
  Exclude:
    - db/migrate/**/*.rb

Metrics/ModuleLength:
  CountAsOne:
    - array
    - hash

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Naming/VariableNumber:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - staging
    - development
    - test

Rails/OutputSafety:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/InverseOf:
  Enabled: false
  
RSpec/ContextWording:
  Enabled: false
    
RSpec/ExampleLength:
  Max: 30

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false
  
RSpec/IndexedLet:
  Enabled: false

RSpec/LetSetup:
  Enabled: false
  
RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/VerifiedDoubles:
  Enabled: false
  
Rails/HasAndBelongsToMany:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false
  
Style/DocumentDynamicEvalDefinition:
  Enabled: false  

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/ModuleFunction:
  EnforcedStyle: extend_self

Style/OpenStructUse:
  Enabled: false

Style/RescueModifier:
  Enabled: false
